baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Blog'
theme = 'paper'

[params]
  # Color theme
  color = 'linen'

  # Header title
  twitter = 'your-twitter-handle'
  github = 'your-github-handle'

  # Avatar
  avatar = 'avatar.jpg'
  name = 'Your Name'
  bio = 'A passionate writer and developer'