baseURL = 'https://blog.techatix.com/'
languageCode = 'en-us'
title = 'Techatix Blog'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

theme = "hugo-bootstrap-theme"
themesdir = "node_modules/@filipecarneiro"
